// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: raj9oz8Dmwv4yPAsi8ZNRE

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { AntdConfigProvider } from "@plasmicpkgs/antd5/skinny/registerConfigProvider";
import { Web3GlobalContext } from "suinova-nft-builder/dist/index.js";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  antdConfigProviderProps?: Partial<
    Omit<React.ComponentProps<typeof AntdConfigProvider>, "children">
  >;
  web3GlobalContextProps?: Partial<
    Omit<React.ComponentProps<typeof Web3GlobalContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, antdConfigProviderProps, web3GlobalContextProps } = props;

  return (
    <AntdConfigProvider
      {...antdConfigProviderProps}
      borderRadius={
        antdConfigProviderProps && "borderRadius" in antdConfigProviderProps
          ? antdConfigProviderProps.borderRadius!
          : 6
      }
      colorBgBase={
        antdConfigProviderProps && "colorBgBase" in antdConfigProviderProps
          ? antdConfigProviderProps.colorBgBase!
          : "#ffffff"
      }
      colorError={
        antdConfigProviderProps && "colorError" in antdConfigProviderProps
          ? antdConfigProviderProps.colorError!
          : "#ff4d4f"
      }
      colorInfo={
        antdConfigProviderProps && "colorInfo" in antdConfigProviderProps
          ? antdConfigProviderProps.colorInfo!
          : "#1677ff"
      }
      colorPrimary={
        antdConfigProviderProps && "colorPrimary" in antdConfigProviderProps
          ? antdConfigProviderProps.colorPrimary!
          : "#1677ff"
      }
      colorSuccess={
        antdConfigProviderProps && "colorSuccess" in antdConfigProviderProps
          ? antdConfigProviderProps.colorSuccess!
          : "#52c41a"
      }
      colorWarning={
        antdConfigProviderProps && "colorWarning" in antdConfigProviderProps
          ? antdConfigProviderProps.colorWarning!
          : "#faad14"
      }
      controlHeight={
        antdConfigProviderProps && "controlHeight" in antdConfigProviderProps
          ? antdConfigProviderProps.controlHeight!
          : 32
      }
      defaultDark={
        antdConfigProviderProps && "defaultDark" in antdConfigProviderProps
          ? antdConfigProviderProps.defaultDark!
          : false
      }
      lineWidth={
        antdConfigProviderProps && "lineWidth" in antdConfigProviderProps
          ? antdConfigProviderProps.lineWidth!
          : 1
      }
      loadingText={
        antdConfigProviderProps && "loadingText" in antdConfigProviderProps
          ? antdConfigProviderProps.loadingText!
          : undefined
      }
      removeLoading={
        antdConfigProviderProps && "removeLoading" in antdConfigProviderProps
          ? antdConfigProviderProps.removeLoading!
          : undefined
      }
      sizeStep={
        antdConfigProviderProps && "sizeStep" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeStep!
          : 4
      }
      sizeUnit={
        antdConfigProviderProps && "sizeUnit" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeUnit!
          : 4
      }
      themeStyles={
        antdConfigProviderProps && "themeStyles" in antdConfigProviderProps
          ? antdConfigProviderProps.themeStyles!
          : true
          ? {
              fontFamily: "Roboto",
              fontSize: "16px",
              fontWeight: "400",
              lineHeight: "1.5",
              color: "#535353",
              letterSpacing: "normal"
            }
          : undefined
      }
      wireframe={
        antdConfigProviderProps && "wireframe" in antdConfigProviderProps
          ? antdConfigProviderProps.wireframe!
          : false
      }
    >
      <Web3GlobalContext
        {...web3GlobalContextProps}
        contractPackageId={
          web3GlobalContextProps &&
          "contractPackageId" in web3GlobalContextProps
            ? web3GlobalContextProps.contractPackageId!
            : "0x2d99da054514ff31c7e7da82751d11bb16b53c66290c435a409e17c8992e35ed"
        }
        createdCollection={
          web3GlobalContextProps &&
          "createdCollection" in web3GlobalContextProps
            ? web3GlobalContextProps.createdCollection!
            : "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b"
        }
        importedCollection={
          web3GlobalContextProps &&
          "importedCollection" in web3GlobalContextProps
            ? web3GlobalContextProps.importedCollection!
            : "0x847d5967dccc496ef9f5dc3673f1e7d174743fbd9d9e29e8c54c33eb74d912d5"
        }
        mintingInfo={
          web3GlobalContextProps && "mintingInfo" in web3GlobalContextProps
            ? web3GlobalContextProps.mintingInfo!
            : {
                id: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                projectId: "raj9oz8Dmwv4yPAsi8ZNRE",
                collectionId:
                  "0xcab8e6fcecc32a31fff0cf16979acf4499520bea2ac6cb0a76ed6ef28acf79ac",
                admin:
                  "0x7c484896d088f2eb3012cac48de62fd4ec02c54540cbb1cd5e312e02216d055a",
                name: "Sui nova demo 6",
                description:
                  "Welcome to Celestial Guardians, a groundbreaking Non-Fungible Token (NFT) collection that blends stunning digital art, cutting-edge blockchain technology, and a vibrant community-driven ecosystem. Launched on the Ethereum blockchain, Celestial Guardians is more than just a collection of unique digital assets\u2014it's a gateway to an immersive universe where creativity, utility, and innovation collide.",
                imageUrl:
                  "https://dev-suinova.s3.ap-southeast-1.amazonaws.com/09c6750e1bddce942757f043be6c994d.jpg",
                royaltyFee: "0",
                hasPresale: false,
                whitelistStartTime: "1748017734",
                whitelistEndTime: "0",
                presaleStartTime: "1748017734",
                presaleEndTime: "0",
                presaleNftPrice: "0",
                presaleWhitelistedUsers: [],
                presaleTotalNft: "0",
                presaleNftPerUser: "0",
                publicSaleStartTime: "1748017734",
                publicSaleEndTime: "0",
                publicNftPrice: "0",
                nftPerUser: "0",
                totalSupply: "0",
                mintedSupply: "0",
                status: "ACTIVE",
                createdAt: "2025-05-23T08:28:54.584Z",
                updatedAt: "2025-05-23T08:28:59.740Z",
                items: [
                  {
                    id: "61",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    name: "Sui demo 6",
                    description:
                      "Welcome to Celestial Guardians, a groundbreaking Non-Fungible Token (NFT) collection that blends stunning digital art, cutting-edge blockchain technology, and a vibrant community-driven ecosystem. Launched on the Ethereum blockchain, Celestial Guardians is more than just a collection of unique digital assets\u2014it's a gateway to an immersive universe where creativity, utility, and innovation collide.",
                    imageUrl:
                      "https://dev-suinova.s3.ap-southeast-1.amazonaws.com/09c6750e1bddce942757f043be6c994d.jpg",
                    attributes: [
                      { value: "red", trait_type: "background" },
                      { value: "gray", trait_type: "background" },
                      { value: "pink", trait_type: "background" }
                    ],
                    creator:
                      "0x7c484896d088f2eb3012cac48de62fd4ec02c54540cbb1cd5e312e02216d055a",
                    createdAt: "2025-05-23T08:28:54.594Z",
                    updatedAt: "2025-05-23T08:28:54.594Z"
                  }
                ],
                visions: [
                  {
                    id: "26",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    description: "Milestone 1",
                    visionTime: "2025-05-23T16:26:55.139Z",
                    createdAt: "2025-05-23T08:28:54.602Z",
                    updatedAt: "2025-05-23T08:28:54.602Z"
                  },
                  {
                    id: "27",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    description: "Milestone 2",
                    visionTime: "2025-05-24T16:26:55.000Z",
                    createdAt: "2025-05-23T08:28:54.602Z",
                    updatedAt: "2025-05-23T08:28:54.602Z"
                  },
                  {
                    id: "28",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    description: "Milestone 3",
                    visionTime: "2025-05-25T16:26:56.000Z",
                    createdAt: "2025-05-23T08:28:54.602Z",
                    updatedAt: "2025-05-23T08:28:54.602Z"
                  }
                ],
                teams: [
                  {
                    id: "32",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    memberName: "Member 1",
                    memberTitle: "Developer",
                    createdAt: "2025-05-23T08:28:54.611Z",
                    updatedAt: "2025-05-23T08:28:54.611Z"
                  },
                  {
                    id: "33",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    memberName: "Member 2",
                    memberTitle: "Developer",
                    createdAt: "2025-05-23T08:28:54.611Z",
                    updatedAt: "2025-05-23T08:28:54.611Z"
                  },
                  {
                    id: "34",
                    launchpadId: "bd850cb3-e4c6-40a0-b675-7b6dddd81b5b",
                    memberName: "Member 3",
                    memberTitle: "Manager",
                    createdAt: "2025-05-23T08:28:54.611Z",
                    updatedAt: "2025-05-23T08:28:54.611Z"
                  }
                ]
              }
        }
      >
        {children}
      </Web3GlobalContext>
    </AntdConfigProvider>
  );
}
